# Generated by Django 5.0.4 on 2024-04-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdb',
            name='role',
            field=models.BooleanField(default=False),
        ),
    ]
