# Generated by Django 5.0.4 on 2024-04-11 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_postsdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postsdb',
            old_name='titre',
            new_name='title',
        ),
    ]
