# Generated by Django 5.0.4 on 2024-04-12 15:52

import base_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=base_app.models.generate_unique_filename),
        ),
        migrations.CreateModel(
            name='CommentsDB',
            fields=[
                ('id_comment', models.AutoField(primary_key=True, serialize=False)),
                ('comment_description', models.CharField(max_length=255)),
                ('id_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.postsdb')),
                ('id_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.usersdb')),
            ],
        ),
    ]
