# Generated by Django 5.0.4 on 2024-04-12 16:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_alter_image_image_commentsdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsdb',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
